/*Auto-generated by FMODEditor*/
namespace Game
{
    public static class FMODName
    {
        public static class Event
        {
        	public const string SFX_ui_进入卡牌 = "event:/SFX/ui_进入卡牌";
        	public const string SFX_ui_选择牌 = "event:/SFX/ui_选择牌";
        	public const string MX_NORMAL_DEMO1 = "event:/MX_NORMAL_DEMO1";
        	public const string MX_COMBAT_DEMO1 = "event:/MX_COMBAT_DEMO1";
        	public const string SFX_ui_出牌 = "event:/SFX/ui_出牌";
        }
        public static class Snapshot
        {
        }
        public static class Bank
        {
        	public const string Master_strings = "bank:/Master.strings";
        	public const string Master = "bank:/Master";
        }
        public static class GlobalParameter
        {
        }
    }
}
